import { Nakshatra } from '../types';

export const NAKSHATRAS: Nakshatra[] = [
  {
    id: 1,
    name: 'Ashwini',
    sanskritName: 'अश्विनी',
    symbol: 'Horse Head',
    rulingPlanet: 'Ketu',
    deity: 'Ashwini Kumaras',
    startDegree: 0,
    endDegree: 13.333,
    rashiId: 1,
    gana: 'Deva',
    nadi: 'Aadi',
    element: 'Fire',
    quality: [
      'Quick', 'Energetic', 'Healing', 'Pioneering', 'Independent',
      'Adventurous', 'Impulsive', 'Courageous',
    ],
    gemstone: 'Cat\'s Eye',
    color: 'Blood Red',
    dashaYears: 7,
    bodyPart: 'Head and Knees',
    animal: 'Horse',
  },
  {
    id: 2,
    name: 'Bharani',
    sanskritName: 'भरणी',
    symbol: 'Yoni (Vulva)',
    rulingPlanet: 'Venus',
    deity: 'Yama',
    startDegree: 13.333,
    endDegree: 26.667,
    rashiId: 1,
    gana: 'Manushya',
    nadi: 'Madhya',
    element: 'Fire',
    quality: [
      'Creative', 'Determined', 'Restrained', 'Intense', 'Loyal',
      'Hardworking', 'Sensual', 'Protective',
    ],
    gemstone: 'Diamond',
    color: 'Blood Red',
    dashaYears: 20,
    bodyPart: 'Head',
    animal: 'Elephant',
  },
  {
    id: 3,
    name: 'Krittika',
    sanskritName: 'कृत्तिका',
    symbol: 'Flame / Razor',
    rulingPlanet: 'Sun',
    deity: 'Agni',
    startDegree: 26.667,
    endDegree: 40,
    rashiId: 1,
    gana: 'Rakshasa',
    nadi: 'Antya',
    element: 'Fire',
    quality: [
      'Sharp', 'Penetrating', 'Ambitious', 'Direct', 'Proud',
      'Nurturing', 'Disciplined', 'Critical',
    ],
    gemstone: 'Ruby',
    color: 'White',
    dashaYears: 6,
    bodyPart: 'Eyes and Face',
    animal: 'Sheep / Goat',
  },
  {
    id: 4,
    name: 'Rohini',
    sanskritName: 'रोहिणी',
    symbol: 'Chariot / Ox Cart',
    rulingPlanet: 'Moon',
    deity: 'Brahma / Prajapati',
    startDegree: 40,
    endDegree: 53.333,
    rashiId: 2,
    gana: 'Manushya',
    nadi: 'Aadi',
    element: 'Earth',
    quality: [
      'Creative', 'Sensual', 'Artistic', 'Grounded', 'Charming',
      'Materialistic', 'Steady', 'Fertile',
    ],
    gemstone: 'Pearl',
    color: 'White',
    dashaYears: 10,
    bodyPart: 'Forehead and Face',
    animal: 'Serpent (Cobra)',
  },
  {
    id: 5,
    name: 'Mrigashira',
    sanskritName: 'मृगशिरा',
    symbol: 'Deer Head',
    rulingPlanet: 'Mars',
    deity: 'Soma (Moon God)',
    startDegree: 53.333,
    endDegree: 66.667,
    rashiId: 2,
    gana: 'Deva',
    nadi: 'Madhya',
    element: 'Earth',
    quality: [
      'Gentle', 'Curious', 'Searching', 'Sensitive', 'Timid',
      'Restless', 'Perceptive', 'Vacillating',
    ],
    gemstone: 'Red Coral',
    color: 'Silver / Grey',
    dashaYears: 7,
    bodyPart: 'Eyes and Chin',
    animal: 'Female Serpent',
  },
  {
    id: 6,
    name: 'Ardra',
    sanskritName: 'आर्द्रा',
    symbol: 'Teardrop / Diamond',
    rulingPlanet: 'Rahu',
    deity: 'Rudra (Storm God)',
    startDegree: 66.667,
    endDegree: 80,
    rashiId: 3,
    gana: 'Manushya',
    nadi: 'Antya',
    element: 'Air',
    quality: [
      'Intense', 'Transformative', 'Rebellious', 'Intellectual', 'Stormy',
      'Perceptive', 'Outspoken', 'Ambitious',
    ],
    gemstone: 'Hessonite (Gomed)',
    color: 'Green',
    dashaYears: 18,
    bodyPart: 'Arms and Shoulders',
    animal: 'Female Dog',
  },
  {
    id: 7,
    name: 'Punarvasu',
    sanskritName: 'पुनर्वसु',
    symbol: 'Bow and Quiver',
    rulingPlanet: 'Jupiter',
    deity: 'Aditi (Mother of Gods)',
    startDegree: 80,
    endDegree: 93.333,
    rashiId: 3,
    gana: 'Deva',
    nadi: 'Aadi',
    element: 'Air',
    quality: [
      'Optimistic', 'Philosophical', 'Renewal', 'Generous', 'Honest',
      'Restless', 'Idealistic', 'Resilient',
    ],
    gemstone: 'Yellow Sapphire',
    color: 'Lead / Ash',
    dashaYears: 16,
    bodyPart: 'Fingers and Nose',
    animal: 'Female Cat',
  },
  {
    id: 8,
    name: 'Pushya',
    sanskritName: 'पुष्य',
    symbol: 'Flower / Circle / Arrow',
    rulingPlanet: 'Saturn',
    deity: 'Brihaspati (Jupiter)',
    startDegree: 93.333,
    endDegree: 106.667,
    rashiId: 4,
    gana: 'Deva',
    nadi: 'Madhya',
    element: 'Water',
    quality: [
      'Nurturing', 'Caring', 'Devoted', 'Nourishing', 'Protective',
      'Traditional', 'Generous', 'Wise',
    ],
    gemstone: 'Blue Sapphire',
    color: 'Red / Crimson',
    dashaYears: 19,
    bodyPart: 'Face and Mouth',
    animal: 'Goat / Ram',
  },
  {
    id: 9,
    name: 'Ashlesha',
    sanskritName: 'आश्लेषा',
    symbol: 'Serpent / Coiled Snake',
    rulingPlanet: 'Mercury',
    deity: 'Naga (Serpent Deities)',
    startDegree: 106.667,
    endDegree: 120,
    rashiId: 4,
    gana: 'Rakshasa',
    nadi: 'Antya',
    element: 'Water',
    quality: [
      'Shrewd', 'Mysterious', 'Perceptive', 'Intense', 'Hypnotic',
      'Manipulative', 'Psychic', 'Tenacious',
    ],
    gemstone: 'Emerald',
    color: 'Blackish Red',
    dashaYears: 17,
    bodyPart: 'Ears and Joints',
    animal: 'Male Cat',
  },
  {
    id: 10,
    name: 'Magha',
    sanskritName: 'मघा',
    symbol: 'Throne / Royal Chamber',
    rulingPlanet: 'Ketu',
    deity: 'Pitris (Ancestors)',
    startDegree: 120,
    endDegree: 133.333,
    rashiId: 5,
    gana: 'Rakshasa',
    nadi: 'Aadi',
    element: 'Fire',
    quality: [
      'Proud', 'Authoritative', 'Noble', 'Respected', 'Ancestral',
      'Arrogant', 'Generous', 'Ambitious',
    ],
    gemstone: 'Cat\'s Eye',
    color: 'Ivory / Cream',
    dashaYears: 7,
    bodyPart: 'Chin and Lips',
    animal: 'Male Rat',
  },
  {
    id: 11,
    name: 'Purva Phalguni',
    sanskritName: 'पूर्व फाल्गुनी',
    symbol: 'Fig Tree / Hammock / Front Legs of Bed',
    rulingPlanet: 'Venus',
    deity: 'Bhaga (God of Delight)',
    startDegree: 133.333,
    endDegree: 146.667,
    rashiId: 5,
    gana: 'Manushya',
    nadi: 'Madhya',
    element: 'Fire',
    quality: [
      'Creative', 'Playful', 'Indulgent', 'Romantic', 'Artistic',
      'Generous', 'Carefree', 'Charming',
    ],
    gemstone: 'Diamond',
    color: 'Light Brown',
    dashaYears: 20,
    bodyPart: 'Genitalia',
    animal: 'Female Rat',
  },
  {
    id: 12,
    name: 'Uttara Phalguni',
    sanskritName: 'उत्तर फाल्गुनी',
    symbol: 'Fig Tree / Back Legs of Bed',
    rulingPlanet: 'Sun',
    deity: 'Aryaman (God of Contracts)',
    startDegree: 146.667,
    endDegree: 160,
    rashiId: 5,
    gana: 'Manushya',
    nadi: 'Antya',
    element: 'Fire',
    quality: [
      'Helpful', 'Charitable', 'Trustworthy', 'Patronizing', 'Bold',
      'Self-reliant', 'Social', 'Principled',
    ],
    gemstone: 'Ruby',
    color: 'Bright Blue',
    dashaYears: 6,
    bodyPart: 'Left Hand and Spine',
    animal: 'Bull / Cow',
  },
  {
    id: 13,
    name: 'Hasta',
    sanskritName: 'हस्त',
    symbol: 'Hand / Fist',
    rulingPlanet: 'Moon',
    deity: 'Savitar (Creative Aspect of Sun)',
    startDegree: 160,
    endDegree: 173.333,
    rashiId: 6,
    gana: 'Deva',
    nadi: 'Aadi',
    element: 'Earth',
    quality: [
      'Skilled', 'Crafty', 'Witty', 'Helpful', 'Resourceful',
      'Nervous', 'Perfectionist', 'Analytical',
    ],
    gemstone: 'Pearl',
    color: 'Deep Green',
    dashaYears: 10,
    bodyPart: 'Hands and Fingers',
    animal: 'Female Buffalo',
  },
  {
    id: 14,
    name: 'Chitra',
    sanskritName: 'चित्रा',
    symbol: 'Bright Jewel / Pearl',
    rulingPlanet: 'Mars',
    deity: 'Tvashtar / Vishwakarma (Divine Architect)',
    startDegree: 173.333,
    endDegree: 186.667,
    rashiId: 6,
    gana: 'Rakshasa',
    nadi: 'Madhya',
    element: 'Fire',
    quality: [
      'Artistic', 'Brilliant', 'Creative', 'Magnetic', 'Passionate',
      'Vain', 'Technically skilled', 'Perfectionist',
    ],
    gemstone: 'Red Coral',
    color: 'Black',
    dashaYears: 7,
    bodyPart: 'Forehead and Neck',
    animal: 'Female Tiger',
  },
  {
    id: 15,
    name: 'Swati',
    sanskritName: 'स्वाती',
    symbol: 'Sword / Young Plant Shoot / Coral',
    rulingPlanet: 'Rahu',
    deity: 'Vayu (Wind God)',
    startDegree: 186.667,
    endDegree: 200,
    rashiId: 7,
    gana: 'Deva',
    nadi: 'Antya',
    element: 'Air',
    quality: [
      'Independent', 'Adaptable', 'Diplomatic', 'Business-minded', 'Restless',
      'Social', 'Idealistic', 'Scattered',
    ],
    gemstone: 'Hessonite (Gomed)',
    color: 'Black / Smoky',
    dashaYears: 18,
    bodyPart: 'Chest and Teeth',
    animal: 'Male Buffalo',
  },
  {
    id: 16,
    name: 'Vishakha',
    sanskritName: 'विशाखा',
    symbol: 'Triumphal Arch / Potter\'s Wheel',
    rulingPlanet: 'Jupiter',
    deity: 'Indra and Agni',
    startDegree: 200,
    endDegree: 213.333,
    rashiId: 7,
    gana: 'Rakshasa',
    nadi: 'Aadi',
    element: 'Fire',
    quality: [
      'Determined', 'Goal-oriented', 'Intense', 'Competitive', 'Charismatic',
      'Jealous', 'Patient', 'Purposeful',
    ],
    gemstone: 'Yellow Sapphire',
    color: 'Golden / Red',
    dashaYears: 16,
    bodyPart: 'Arms and Breasts',
    animal: 'Male Tiger',
  },
  {
    id: 17,
    name: 'Anuradha',
    sanskritName: 'अनुराधा',
    symbol: 'Staff / Lotus Flower',
    rulingPlanet: 'Saturn',
    deity: 'Mitra (God of Friendship)',
    startDegree: 213.333,
    endDegree: 226.667,
    rashiId: 8,
    gana: 'Deva',
    nadi: 'Madhya',
    element: 'Water',
    quality: [
      'Devoted', 'Friendly', 'Organized', 'Balanced', 'Spiritual',
      'Cooperative', 'Passionate', 'Persistent',
    ],
    gemstone: 'Blue Sapphire',
    color: 'Reddish Brown',
    dashaYears: 19,
    bodyPart: 'Heart and Stomach',
    animal: 'Female Deer / Hare',
  },
  {
    id: 18,
    name: 'Jyeshtha',
    sanskritName: 'ज्येष्ठा',
    symbol: 'Circular Amulet / Umbrella / Earring',
    rulingPlanet: 'Mercury',
    deity: 'Indra (King of Gods)',
    startDegree: 226.667,
    endDegree: 240,
    rashiId: 8,
    gana: 'Rakshasa',
    nadi: 'Antya',
    element: 'Water',
    quality: [
      'Responsible', 'Protective', 'Ambitious', 'Proud', 'Authoritative',
      'Arrogant', 'Sharp-tongued', 'Leadership',
    ],
    gemstone: 'Emerald',
    color: 'Cream / Off-white',
    dashaYears: 17,
    bodyPart: 'Tongue, Right Side, Neck',
    animal: 'Male Deer / Hare',
  },
  {
    id: 19,
    name: 'Mula',
    sanskritName: 'मूल',
    symbol: 'Tied Bundle of Roots / Elephant Goad',
    rulingPlanet: 'Ketu',
    deity: 'Nirriti (Goddess of Destruction)',
    startDegree: 240,
    endDegree: 253.333,
    rashiId: 9,
    gana: 'Rakshasa',
    nadi: 'Aadi',
    element: 'Fire',
    quality: [
      'Investigative', 'Rooting out', 'Philosophical', 'Destructive', 'Transformative',
      'Honest', 'Blunt', 'Deep',
    ],
    gemstone: 'Cat\'s Eye',
    color: 'Brown / Yellow-red',
    dashaYears: 7,
    bodyPart: 'Feet and Left Side',
    animal: 'Male Dog',
  },
  {
    id: 20,
    name: 'Purva Ashadha',
    sanskritName: 'पूर्वाषाढ़',
    symbol: 'Elephant Tusk / Fan / Winnowing Basket',
    rulingPlanet: 'Venus',
    deity: 'Apas (Water Goddess)',
    startDegree: 253.333,
    endDegree: 266.667,
    rashiId: 9,
    gana: 'Manushya',
    nadi: 'Madhya',
    element: 'Fire',
    quality: [
      'Proud', 'Invincible', 'Philosophical', 'Optimistic', 'Bold',
      'Stubborn', 'Outspoken', 'Wise',
    ],
    gemstone: 'Diamond',
    color: 'Black',
    dashaYears: 20,
    bodyPart: 'Thighs and Back',
    animal: 'Male Monkey',
  },
  {
    id: 21,
    name: 'Uttara Ashadha',
    sanskritName: 'उत्तराषाढ़',
    symbol: 'Elephant Tusk / Small Bed',
    rulingPlanet: 'Sun',
    deity: 'Vishwadevas (Universal Gods)',
    startDegree: 266.667,
    endDegree: 280,
    rashiId: 9,
    gana: 'Manushya',
    nadi: 'Antya',
    element: 'Fire',
    quality: [
      'Victorious', 'Ethical', 'Hardworking', 'Responsible', 'Sincere',
      'Principled', 'Inflexible', 'Noble',
    ],
    gemstone: 'Ruby',
    color: 'Copper / Yellow',
    dashaYears: 6,
    bodyPart: 'Thighs',
    animal: 'Female Mongoose',
  },
  {
    id: 22,
    name: 'Shravana',
    sanskritName: 'श्रवण',
    symbol: 'Three Footprints / Ear / Trident',
    rulingPlanet: 'Moon',
    deity: 'Vishnu (Preserver God)',
    startDegree: 280,
    endDegree: 293.333,
    rashiId: 10,
    gana: 'Deva',
    nadi: 'Aadi',
    element: 'Air',
    quality: [
      'Learned', 'Listening', 'Wise', 'Scholarly', 'Connected',
      'Perceptive', 'Gossip-prone', 'Sensitive',
    ],
    gemstone: 'Pearl',
    color: 'Light Blue',
    dashaYears: 10,
    bodyPart: 'Ears and Genitalia',
    animal: 'Female Monkey',
  },
  {
    id: 23,
    name: 'Dhanishtha',
    sanskritName: 'धनिष्ठा',
    symbol: 'Drum / Flute',
    rulingPlanet: 'Mars',
    deity: 'Ashta Vasus (Eight Elemental Gods)',
    startDegree: 293.333,
    endDegree: 306.667,
    rashiId: 10,
    gana: 'Rakshasa',
    nadi: 'Madhya',
    element: 'Ether',
    quality: [
      'Rhythmic', 'Musical', 'Wealthy', 'Charitable', 'Energetic',
      'Boastful', 'Ambitious', 'Sociable',
    ],
    gemstone: 'Red Coral',
    color: 'Silver / Golden',
    dashaYears: 7,
    bodyPart: 'Back, Ankles, Knee',
    animal: 'Female Lion',
  },
  {
    id: 24,
    name: 'Shatabhisha',
    sanskritName: 'शतभिषा',
    symbol: 'Empty Circle / 100 Stars / Flower',
    rulingPlanet: 'Rahu',
    deity: 'Varuna (God of Cosmic Waters)',
    startDegree: 306.667,
    endDegree: 320,
    rashiId: 11,
    gana: 'Rakshasa',
    nadi: 'Antya',
    element: 'Air',
    quality: [
      'Mystical', 'Secretive', 'Healing', 'Eccentric', 'Scientific',
      'Philosophical', 'Reclusive', 'Meditative',
    ],
    gemstone: 'Hessonite (Gomed)',
    color: 'Blue-green',
    dashaYears: 18,
    bodyPart: 'Right Thigh',
    animal: 'Female Horse',
  },
  {
    id: 25,
    name: 'Purva Bhadrapada',
    sanskritName: 'पूर्वभाद्रपद',
    symbol: 'Sword / Two Front Legs of Funeral Cot',
    rulingPlanet: 'Jupiter',
    deity: 'Aja Ekapada (One-footed Serpent / Rudra)',
    startDegree: 320,
    endDegree: 333.333,
    rashiId: 11,
    gana: 'Manushya',
    nadi: 'Aadi',
    element: 'Ether',
    quality: [
      'Passionate', 'Spiritual', 'Intense', 'Visionary', 'Eccentric',
      'Agitated', 'Ascetic', 'Transformative',
    ],
    gemstone: 'Yellow Sapphire',
    color: 'Silver / Lead',
    dashaYears: 16,
    bodyPart: 'Ribs and Left Thigh',
    animal: 'Male Lion',
  },
  {
    id: 26,
    name: 'Uttara Bhadrapada',
    sanskritName: 'उत्तरभाद्रपद',
    symbol: 'Twins / Back Legs of Funeral Cot / Snake in the Water',
    rulingPlanet: 'Saturn',
    deity: 'Ahir Budhnya (Serpent of the Deep)',
    startDegree: 333.333,
    endDegree: 346.667,
    rashiId: 12,
    gana: 'Manushya',
    nadi: 'Madhya',
    element: 'Ether',
    quality: [
      'Deep', 'Wise', 'Compassionate', 'Spiritual', 'Disciplined',
      'Restrained', 'Philosophical', 'Scholarly',
    ],
    gemstone: 'Blue Sapphire',
    color: 'Purple / Violet',
    dashaYears: 19,
    bodyPart: 'Legs and Ankles',
    animal: 'Female Cow',
  },
  {
    id: 27,
    name: 'Revati',
    sanskritName: 'रेवती',
    symbol: 'Fish / Drum / Pair of Fish',
    rulingPlanet: 'Mercury',
    deity: 'Pushan (Nourisher / Guide)',
    startDegree: 346.667,
    endDegree: 360,
    rashiId: 12,
    gana: 'Deva',
    nadi: 'Antya',
    element: 'Ether',
    quality: [
      'Nurturing', 'Spiritual', 'Compassionate', 'Creative', 'Sensitive',
      'Naive', 'Idealistic', 'Empathetic',
    ],
    gemstone: 'Emerald',
    color: 'Brown / Tawny',
    dashaYears: 17,
    bodyPart: 'Feet and Ankles',
    animal: 'Female Elephant',
  },
];

// Utility: Get nakshatra by sidereal longitude (0-360)
export function getNakshatraByLongitude(longitude: number): Nakshatra {
  const normalized = ((longitude % 360) + 360) % 360;
  const index = Math.floor(normalized / 13.333333333);
  const clampedIndex = Math.min(index, 26);
  return NAKSHATRAS[clampedIndex];
}

// Utility: Get pada (quarter) within nakshatra
export function getNakshatraPada(longitude: number): number {
  const normalized = ((longitude % 360) + 360) % 360;
  const positionInNakshatra = normalized % 13.333333333;
  return Math.floor(positionInNakshatra / 3.333333333) + 1;
}

export default NAKSHATRAS;
