import { Rashi } from '../types';

export const RASHIS: Rashi[] = [
  {
    id: 1,
    name: 'Mesha',
    westernName: 'Aries',
    symbol: '♈',
    rulingPlanet: 'Mars',
    element: 'Fire',
    quality: 'Cardinal',
    startDegree: 0,
    endDegree: 30,
    personalityTraits: [
      'Courageous', 'Energetic', 'Pioneering', 'Impulsive', 'Independent',
      'Assertive', 'Competitive', 'Direct', 'Adventurous', 'Short-tempered',
    ],
    bodyParts: ['Head', 'Brain', 'Eyes', 'Face'],
    favorableActivities: [
      'Starting new ventures', 'Sports and physical activity', 'Leadership roles',
      'Pioneering work', 'Military and law enforcement', 'Surgery',
    ],
    unfavorableActivities: [
      'Routine desk work', 'Waiting and patience-requiring tasks',
      'Diplomacy-heavy negotiations', 'Secretarial roles',
    ],
    compatibleRashis: [5, 9, 3, 11],
    vedicDescription: 'Mesha is the first sign of the zodiac, ruled by the fierce Mars (Mangal). It is a fire sign, cardinal in nature, representing new beginnings, raw energy, and the pioneering spirit. The native of Mesha is courageous, energetic, and a natural leader, though prone to impulsiveness and anger.',
  },
  {
    id: 2,
    name: 'Vrishabha',
    westernName: 'Taurus',
    symbol: '♉',
    rulingPlanet: 'Venus',
    element: 'Earth',
    quality: 'Fixed',
    startDegree: 30,
    endDegree: 60,
    personalityTraits: [
      'Patient', 'Reliable', 'Stubborn', 'Materialistic', 'Sensual',
      'Artistic', 'Determined', 'Practical', 'Loyal', 'Possessive',
    ],
    bodyParts: ['Throat', 'Neck', 'Vocal Cords', 'Thyroid'],
    favorableActivities: [
      'Arts and crafts', 'Finance and banking', 'Agriculture', 'Music',
      'Cooking', 'Real estate', 'Luxury goods',
    ],
    unfavorableActivities: [
      'Sudden changes and risks', 'Confrontational situations',
      'Fast-paced environments', 'Abstract work without material results',
    ],
    compatibleRashis: [6, 10, 2, 12],
    vedicDescription: 'Vrishabha is ruled by Venus (Shukra), the planet of beauty, luxury, and love. As a fixed earth sign, it represents stability, determination, and an appreciation for the material world. The Moon is exalted here, making it a highly fertile and receptive sign. Vrishabha natives are steady, sensual, and deeply connected to nature and the arts.',
  },
  {
    id: 3,
    name: 'Mithuna',
    westernName: 'Gemini',
    symbol: '♊',
    rulingPlanet: 'Mercury',
    element: 'Air',
    quality: 'Mutable',
    startDegree: 60,
    endDegree: 90,
    personalityTraits: [
      'Intellectual', 'Versatile', 'Communicative', 'Witty', 'Curious',
      'Adaptable', 'Inconsistent', 'Social', 'Clever', 'Restless',
    ],
    bodyParts: ['Arms', 'Hands', 'Shoulders', 'Lungs', 'Nervous System'],
    favorableActivities: [
      'Writing and publishing', 'Teaching', 'Journalism', 'Sales',
      'Networking', 'Research', 'Travel', 'Technology',
    ],
    unfavorableActivities: [
      'Manual repetitive labor', 'Isolated work', 'Long-term single focus',
      'Deeply emotional introspective work',
    ],
    compatibleRashis: [1, 5, 7, 11],
    vedicDescription: 'Mithuna is ruled by Mercury (Budha), the planet of intellect and communication. It is a mutable air sign representing duality, versatility, and the exchange of ideas. The native of Mithuna is highly intelligent, adaptable, and skilled in communication, though may struggle with consistency and depth.',
  },
  {
    id: 4,
    name: 'Karka',
    westernName: 'Cancer',
    symbol: '♋',
    rulingPlanet: 'Moon',
    element: 'Water',
    quality: 'Cardinal',
    startDegree: 90,
    endDegree: 120,
    personalityTraits: [
      'Nurturing', 'Intuitive', 'Sensitive', 'Protective', 'Emotional',
      'Home-loving', 'Tenacious', 'Moody', 'Imaginative', 'Loyal',
    ],
    bodyParts: ['Chest', 'Breasts', 'Stomach', 'Digestive System'],
    favorableActivities: [
      'Child care and teaching', 'Nursing and healthcare', 'Cooking',
      'Psychology', 'History and heritage work', 'Real estate',
    ],
    unfavorableActivities: [
      'Harsh competitive environments', 'Long separations from home',
      'Overly logical tasks without emotional components',
    ],
    compatibleRashis: [4, 8, 12, 3],
    vedicDescription: 'Karka is ruled by the Moon (Chandra), the mind and mother of the cosmos. As a cardinal water sign, it embodies nurturing, protection, and deep emotional sensitivity. Jupiter is exalted in Karka, signifying wisdom emerging from the depths of feeling. The native is deeply caring, family-oriented, and highly intuitive.',
  },
  {
    id: 5,
    name: 'Simha',
    westernName: 'Leo',
    symbol: '♌',
    rulingPlanet: 'Sun',
    element: 'Fire',
    quality: 'Fixed',
    startDegree: 120,
    endDegree: 150,
    personalityTraits: [
      'Proud', 'Generous', 'Theatrical', 'Dominant', 'Creative',
      'Warm-hearted', 'Stubborn', 'Dignified', 'Loyal', 'Charismatic',
    ],
    bodyParts: ['Heart', 'Spine', 'Upper Back'],
    favorableActivities: [
      'Leadership and management', 'Arts and performance', 'Politics',
      'Education', 'Speculation', 'Sports', 'Entertainment',
    ],
    unfavorableActivities: [
      'Subordinate positions', 'Anonymity', 'Humbling work',
      'Detailed clerical tasks',
    ],
    compatibleRashis: [1, 9, 4, 10],
    vedicDescription: 'Simha is the sign of the Sun (Surya), the soul and authority of the cosmos. As a fixed fire sign, it represents royalty, dignity, and creative self-expression. The native of Simha radiates confidence, warmth, and natural leadership. They are generous to a fault and desire to be the center of attention.',
  },
  {
    id: 6,
    name: 'Kanya',
    westernName: 'Virgo',
    symbol: '♍',
    rulingPlanet: 'Mercury',
    element: 'Earth',
    quality: 'Mutable',
    startDegree: 150,
    endDegree: 180,
    personalityTraits: [
      'Analytical', 'Meticulous', 'Service-oriented', 'Critical', 'Practical',
      'Intelligent', 'Modest', 'Perfectionist', 'Helpful', 'Discriminating',
    ],
    bodyParts: ['Intestines', 'Lower Abdomen', 'Digestive System'],
    favorableActivities: [
      'Healthcare and medicine', 'Research and analysis', 'Accounting',
      'Editing and writing', 'Service industries', 'Yoga and wellness',
    ],
    unfavorableActivities: [
      'Spontaneous risk-taking', 'Abstract speculative ventures',
      'Spotlight performance roles',
    ],
    compatibleRashis: [2, 6, 10, 4],
    vedicDescription: 'Kanya is ruled by Mercury (Budha) and is the sign where Mercury is both exalted and in its own sign, making it the most intellectual and discriminating of all signs. It is a mutable earth sign representing analysis, purification, and practical service. The native of Kanya has a highly discerning intellect and a deep desire to be of use.',
  },
  {
    id: 7,
    name: 'Tula',
    westernName: 'Libra',
    symbol: '♎',
    rulingPlanet: 'Venus',
    element: 'Air',
    quality: 'Cardinal',
    startDegree: 180,
    endDegree: 210,
    personalityTraits: [
      'Diplomatic', 'Fair-minded', 'Social', 'Indecisive', 'Elegant',
      'Romantic', 'Intellectual', 'Charming', 'Idealistic', 'Gracious',
    ],
    bodyParts: ['Kidneys', 'Lower Back', 'Lumbar Region'],
    favorableActivities: [
      'Law and justice', 'Diplomacy', 'Arts and design',
      'Counseling', 'Fashion', 'Public relations', 'Partnership ventures',
    ],
    unfavorableActivities: [
      'Quick solo decisions', 'Confrontational debates without mediation',
      'Harsh physical labor', 'Isolation',
    ],
    compatibleRashis: [2, 6, 3, 11],
    vedicDescription: 'Tula is ruled by Venus (Shukra) and is the sign where Saturn is exalted and the Sun is debilitated, revealing the tension between ego and social harmony. As a cardinal air sign, Tula represents justice, balance, and the ideal of relationship. The native seeks harmony above all and is naturally gifted in diplomacy and the arts.',
  },
  {
    id: 8,
    name: 'Vrischika',
    westernName: 'Scorpio',
    symbol: '♏',
    rulingPlanet: 'Mars',
    element: 'Water',
    quality: 'Fixed',
    startDegree: 210,
    endDegree: 240,
    personalityTraits: [
      'Intense', 'Mysterious', 'Transformative', 'Perceptive', 'Secretive',
      'Passionate', 'Willful', 'Psychic', 'Magnetic', 'Vengeful',
    ],
    bodyParts: ['Genitalia', 'Pelvis', 'Excretory System'],
    favorableActivities: [
      'Research and investigation', 'Surgery', 'Psychology',
      'Occult sciences', 'Mining', 'Military', 'Transformation work',
    ],
    unfavorableActivities: [
      'Superficial social interactions', 'Light entertainment',
      'Work requiring trust without verification', 'Passive activities',
    ],
    compatibleRashis: [4, 8, 12, 7],
    vedicDescription: 'Vrischika is co-ruled by Mars (Mangal) and Ketu, making it the sign of hidden power, transformation, and occult knowledge. As a fixed water sign, it represents depth, regeneration, and the mysteries of death and rebirth. The Moon is debilitated here, revealing the sign\'s challenge to the reflective, peaceful mind. The native of Vrischika is intensely perceptive and magnetically powerful.',
  },
  {
    id: 9,
    name: 'Dhanu',
    westernName: 'Sagittarius',
    symbol: '♐',
    rulingPlanet: 'Jupiter',
    element: 'Fire',
    quality: 'Mutable',
    startDegree: 240,
    endDegree: 270,
    personalityTraits: [
      'Philosophical', 'Optimistic', 'Adventurous', 'Honest', 'Restless',
      'Enthusiastic', 'Generous', 'Blunt', 'Freedom-loving', 'Spiritual',
    ],
    bodyParts: ['Hips', 'Thighs', 'Liver', 'Sciatic Nerve'],
    favorableActivities: [
      'Teaching and philosophy', 'Travel and exploration', 'Religion and spirituality',
      'Law and publishing', 'Sports (especially riding)', 'International work',
    ],
    unfavorableActivities: [
      'Detail-oriented administrative work', 'Confined roles',
      'Repetitive routines', 'Work requiring emotional delicacy',
    ],
    compatibleRashis: [1, 5, 7, 9],
    vedicDescription: 'Dhanu is ruled by Jupiter (Guru/Brihaspati), the great benefic and teacher of the cosmos. As a mutable fire sign, it represents philosophy, higher learning, and the quest for truth. The native of Dhanu is expansive, optimistic, and deeply philosophical, always seeking a higher meaning and the wisdom of distant horizons.',
  },
  {
    id: 10,
    name: 'Makara',
    westernName: 'Capricorn',
    symbol: '♑',
    rulingPlanet: 'Saturn',
    element: 'Earth',
    quality: 'Cardinal',
    startDegree: 270,
    endDegree: 300,
    personalityTraits: [
      'Ambitious', 'Disciplined', 'Patient', 'Pragmatic', 'Responsible',
      'Cautious', 'Hardworking', 'Traditional', 'Status-conscious', 'Pessimistic',
    ],
    bodyParts: ['Knees', 'Joints', 'Bones', 'Skin'],
    favorableActivities: [
      'Business and administration', 'Government and politics', 'Engineering',
      'Finance', 'Agriculture', 'Architecture', 'Long-term planning',
    ],
    unfavorableActivities: [
      'Spontaneous activities', 'Emotional expressive arts', 'Short-term ventures',
      'Frivolous socializing',
    ],
    compatibleRashis: [2, 6, 5, 10],
    vedicDescription: 'Makara is ruled by Saturn (Shani), the karmic disciplinarian. Mars is exalted here, and Jupiter is debilitated, reflecting the dominance of material ambition over unbounded idealism. As a cardinal earth sign, Makara represents ambition, structure, and the patient climb toward achievement. The native of Makara is disciplined, responsible, and built for long-term success.',
  },
  {
    id: 11,
    name: 'Kumbha',
    westernName: 'Aquarius',
    symbol: '♒',
    rulingPlanet: 'Saturn',
    element: 'Air',
    quality: 'Fixed',
    startDegree: 300,
    endDegree: 330,
    personalityTraits: [
      'Humanitarian', 'Innovative', 'Independent', 'Eccentric', 'Intellectual',
      'Detached', 'Idealistic', 'Progressive', 'Rebellious', 'Perceptive',
    ],
    bodyParts: ['Ankles', 'Calves', 'Circulatory System'],
    favorableActivities: [
      'Science and technology', 'Social reform and activism', 'Astrology',
      'Group work and organizations', 'Humanitarian causes', 'Research',
    ],
    unfavorableActivities: [
      'Deeply personal emotional work', 'Routine without purpose',
      'Authority-heavy hierarchies', 'Isolated work without social component',
    ],
    compatibleRashis: [1, 3, 7, 11],
    vedicDescription: 'Kumbha is co-ruled by Saturn (Shani) and Rahu, making it the sign of the collective, the future, and unconventional thinking. As a fixed air sign, it represents humanitarianism, innovation, and the broader vision for society. The native of Kumbha is a visionary who works for the collective good, often ahead of their time.',
  },
  {
    id: 12,
    name: 'Meena',
    westernName: 'Pisces',
    symbol: '♓',
    rulingPlanet: 'Jupiter',
    element: 'Water',
    quality: 'Mutable',
    startDegree: 330,
    endDegree: 360,
    personalityTraits: [
      'Compassionate', 'Intuitive', 'Spiritual', 'Imaginative', 'Empathetic',
      'Selfless', 'Dreamy', 'Naive', 'Artistic', 'Escapist',
    ],
    bodyParts: ['Feet', 'Lymphatic System', 'Immune System'],
    favorableActivities: [
      'Healing and medicine', 'Music and art', 'Spirituality and mysticism',
      'Charity work', 'Writing (especially poetry)', 'Film and photography',
    ],
    unfavorableActivities: [
      'Cold analytical work', 'Highly competitive environments',
      'Mundane administrative tasks', 'Work requiring harsh boundaries',
    ],
    compatibleRashis: [4, 8, 12, 6],
    vedicDescription: 'Meena is ruled by Jupiter (Guru) and is the sign where Venus is exalted and Mercury is debilitated. As the last sign of the zodiac, Meena represents the dissolution of boundaries, deep spirituality, and the merging of the individual soul (jiva) with the universal consciousness. The native of Meena is exceptionally compassionate, intuitive, and spiritually inclined.',
  },
];

export default RASHIS;
