import { useState, useRef, useCallback, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useStore, KundliData } from '@/store'
import { usePremium } from '@/hooks/usePremium'
import PremiumGate from '@/components/Premium/PremiumGate'
import { Link } from 'react-router-dom'
import {
  ArrowLeft, Play, Download, Share2, Mail, MessageCircle, Loader2,
  Star, Clock, Shield, TrendingUp, Sparkles, ChevronRight, Lock
} from 'lucide-react'
import { RASHI_DATA, NAKSHATRA_NAMES } from '@/lib/vedic-constants'

// ─── Video Scene Types ────────────────────────────────────────────────────

interface VideoScene {
  title: string
  subtitle?: string
  lines: string[]
  icon: string
  duration: number // seconds
  color: string
}

// ─── Scene Generator ──────────────────────────────────────────────────────

const RASHIS_SIMPLE = ['Mesha', 'Vrishabha', 'Mithuna', 'Karka', 'Simha', 'Kanya', 'Tula', 'Vrischika', 'Dhanu', 'Makara', 'Kumbha', 'Meena']

function generateScenes(kundli: KundliData): VideoScene[] {
  const lagna = RASHI_DATA[kundli.ascendant.rashiIndex]
  const nakshatra = NAKSHATRA_NAMES[kundli.ascendant.nakshatraIndex] ?? 'Unknown'
  const sun = kundli.planets.find(p => p.name === 'Sun')
  const moon = kundli.planets.find(p => p.name === 'Moon')
  const sunRashi = sun ? RASHIS_SIMPLE[sun.rashiIndex] : 'Unknown'
  const moonRashi = moon ? RASHIS_SIMPLE[moon.rashiIndex] : 'Unknown'

  const { currentMahadasha, currentAntardasha } = kundli.dashas
  const now = new Date()
  const currentYear = now.getFullYear()

  // Dignity summary
  const exalted = kundli.planets.filter(p => p.dignity === 'Exalted').map(p => p.name)
  const debilitated = kundli.planets.filter(p => p.dignity === 'Debilitated').map(p => p.name)
  const retrograde = kundli.planets.filter(p => p.isRetrograde).map(p => p.name)

  // Yoga highlights
  const topYogas = kundli.yogas.slice(0, 3)

  // Dosha warnings
  const doshas = kundli.doshas

  const scenes: VideoScene[] = []

  // Scene 1: Intro
  scenes.push({
    title: `${kundli.name}'s Kundli`,
    subtitle: 'Vedic Birth Chart Analysis',
    lines: [
      `${lagna?.symbol ?? '♈'} ${lagna?.name ?? ''} Lagna (${lagna?.western ?? ''})`,
      `Birth Nakshatra: ${nakshatra}`,
      `Sun: ${sunRashi} · Moon: ${moonRashi}`,
      `Generated by Nakshatra App`,
    ],
    icon: '⬡',
    duration: 8,
    color: '#FFB347',
  })

  // Scene 2: Planetary Overview
  const planetLines = kundli.planets.map(p => {
    const rashi = RASHIS_SIMPLE[p.rashiIndex]
    const ret = p.isRetrograde ? ' ℞' : ''
    const dig = p.dignity !== 'Neutral' ? ` (${p.dignity})` : ''
    return `${p.name}${ret}: ${rashi} · H${p.houseNumber}${dig}`
  })
  scenes.push({
    title: 'Planetary Positions',
    subtitle: 'The Nine Grahas at Birth',
    lines: planetLines,
    icon: '🪐',
    duration: 12,
    color: '#7DF9FF',
  })

  // Scene 3: Key Strengths
  const strengthLines: string[] = []
  if (exalted.length > 0) strengthLines.push(`Exalted: ${exalted.join(', ')} — peak power`)
  if (retrograde.length > 0) strengthLines.push(`Retrograde: ${retrograde.join(', ')} — deep inner work`)
  if (debilitated.length > 0) strengthLines.push(`Debilitated: ${debilitated.join(', ')} — growth areas`)

  const kendraP = kundli.planets.filter(p => [1, 4, 7, 10].includes(p.houseNumber))
  if (kendraP.length > 0) strengthLines.push(`Kendra planets: ${kendraP.map(p => p.name).join(', ')}`)

  const trikonaP = kundli.planets.filter(p => [1, 5, 9].includes(p.houseNumber))
  if (trikonaP.length > 0) strengthLines.push(`Trikona planets: ${trikonaP.map(p => p.name).join(', ')}`)

  scenes.push({
    title: 'Key Strengths',
    subtitle: 'Your Cosmic Advantages',
    lines: strengthLines.length > 0 ? strengthLines : ['Balanced chart with steady planetary energies'],
    icon: '💪',
    duration: 10,
    color: '#22c55e',
  })

  // Scene 4: Yogas
  if (topYogas.length > 0) {
    scenes.push({
      title: 'Yogas Detected',
      subtitle: `${kundli.yogas.length} yoga(s) found in your chart`,
      lines: topYogas.map(y => `${y.name} (${y.strength}) — ${y.description.slice(0, 80)}...`),
      icon: '✨',
      duration: 10,
      color: '#a855f7',
    })
  }

  // Scene 5: Current Dasha Period
  scenes.push({
    title: 'Current Dasha Period',
    subtitle: 'Your Cosmic Season Right Now',
    lines: [
      `Mahadasha: ${currentMahadasha.planet} (until ${new Date(currentMahadasha.endDate).getFullYear()})`,
      `Antardasha: ${currentAntardasha.planet}`,
      '',
      getDashaPrediction(currentMahadasha.planet),
    ],
    icon: '🔮',
    duration: 10,
    color: '#FFD700',
  })

  // Scene 6: Week & Month Ahead (transit-based)
  scenes.push({
    title: `${currentYear} Forecast`,
    subtitle: 'Week, Month & Year Outlook',
    lines: [
      `This Week: ${getWeekForecast(moonRashi)}`,
      '',
      `This Month: ${getMonthForecast(sunRashi, currentMahadasha.planet)}`,
      '',
      `Year Theme: ${getYearTheme(currentMahadasha.planet)}`,
    ],
    icon: '📅',
    duration: 12,
    color: '#3b82f6',
  })

  // Scene 7: Doshas & Remedies
  if (doshas.length > 0) {
    const doshaLines = doshas.flatMap(d => [
      `⚠ ${d.name} (${d.severity})`,
      `  ${d.description.slice(0, 80)}`,
    ])
    scenes.push({
      title: 'Doshas & Remedies',
      subtitle: 'Areas Needing Attention',
      lines: [...doshaLines, '', 'See Remedies page for detailed guidance'],
      icon: '🛡️',
      duration: 10,
      color: '#ef4444',
    })
  }

  // Scene 8: Remedies & Rituals
  const remedyLines = getRemedies(currentMahadasha.planet, doshas.map(d => d.name))
  scenes.push({
    title: 'Remedies & Rituals',
    subtitle: 'Strengthen Your Chart',
    lines: remedyLines,
    icon: '🙏',
    duration: 10,
    color: '#f97316',
  })

  // Scene 9: Positive Highlights
  scenes.push({
    title: 'The Good Parts',
    subtitle: 'Blessings in Your Chart',
    lines: getPositiveHighlights(kundli),
    icon: '🌟',
    duration: 10,
    color: '#eab308',
  })

  // Scene 10: Closing
  scenes.push({
    title: 'Hari Om',
    subtitle: `${kundli.name}, may the stars guide your path`,
    lines: [
      'This analysis covers your birth chart highlights,',
      'current dasha period, and near-term forecasts.',
      '',
      'For deeper insights, explore the full Kundli',
      'with Ashtakvarga, Shadbala, and Varshfal.',
      '',
      'Generated by Nakshatra · bitsizegyaan.com',
    ],
    icon: '🙏',
    duration: 8,
    color: '#FFB347',
  })

  return scenes
}

function getDashaPrediction(planet: string): string {
  const predictions: Record<string, string> = {
    Sun: 'Focus on leadership, authority, and health. Government-related matters may arise.',
    Moon: 'Emotional growth and domestic changes. Mother figures become prominent.',
    Mars: 'High energy period. Property matters, courage, and physical activity peak.',
    Mercury: 'Excellent for business, education, and communication. Travel likely.',
    Jupiter: 'Most auspicious period. Wisdom, expansion, marriage, and fortune.',
    Venus: 'Love, luxury, creativity flourish. Material comforts increase significantly.',
    Saturn: 'Period of discipline and hard work. Slow but lasting achievements.',
    Rahu: 'Unconventional opportunities. Foreign connections. Sudden changes possible.',
    Ketu: 'Spiritual awakening and detachment. Past-life karmas resolve.',
  }
  return predictions[planet] ?? 'A period of growth and transformation.'
}

function getWeekForecast(moonRashi: string): string {
  const forecasts: Record<string, string> = {
    Mesha: 'High energy. Take initiative on pending tasks.',
    Vrishabha: 'Focus on finances. A good week for stability.',
    Mithuna: 'Communication peaks. Network and connect.',
    Karka: 'Emotional clarity. Spend time with family.',
    Simha: 'Confidence rises. Creative projects shine.',
    Kanya: 'Analytical week. Health checkup recommended.',
    Tula: 'Relationships highlighted. Seek balance.',
    Vrischika: 'Transformation energy. Let go of what no longer serves.',
    Dhanu: 'Learning and travel favored. Expand your horizons.',
    Makara: 'Career focus. Professional recognition possible.',
    Kumbha: 'Social connections expand. Innovative ideas flow.',
    Meena: 'Spiritual week. Meditation brings clarity.',
  }
  return forecasts[moonRashi] ?? 'A balanced week with steady progress.'
}

function getMonthForecast(sunRashi: string, dashaPlanet: string): string {
  return `With Sun in ${sunRashi} and ${dashaPlanet} Mahadasha active, this month favors disciplined effort. Key planetary transits support progress in career and personal growth. Mid-month brings important communications.`
}

function getYearTheme(dashaPlanet: string): string {
  const themes: Record<string, string> = {
    Sun: 'Self-discovery, authority, and vitality',
    Moon: 'Emotional growth, home, and nurturing',
    Mars: 'Action, courage, and property matters',
    Mercury: 'Learning, business, and communication',
    Jupiter: 'Expansion, fortune, and spiritual growth',
    Venus: 'Love, creativity, and material abundance',
    Saturn: 'Discipline, karma, and lasting foundations',
    Rahu: 'Ambition, foreign ties, and transformation',
    Ketu: 'Spirituality, detachment, and liberation',
  }
  return themes[dashaPlanet] ?? 'Growth and transformation'
}

function getRemedies(dashaPlanet: string, doshaNames: string[]): string[] {
  const lines: string[] = []
  const planetRemedies: Record<string, string[]> = {
    Sun: ['Offer water to Sun at sunrise daily', 'Chant Aditya Hridayam on Sundays', 'Wear Ruby after consultation'],
    Moon: ['Wear Pearl or Moonstone', 'Donate white items on Mondays', 'Meditate during moonrise'],
    Mars: ['Worship Hanuman on Tuesdays', 'Chant Mangal Beej Mantra', 'Donate red lentils on Tuesdays'],
    Mercury: ['Worship Lord Vishnu on Wednesdays', 'Keep Emerald after consultation', 'Practice learning daily'],
    Jupiter: ['Worship Jupiter on Thursdays', 'Wear Yellow Sapphire', 'Donate yellow items to Brahmins'],
    Venus: ['Worship Lakshmi on Fridays', 'Wear Diamond or White Sapphire', 'Offer white flowers'],
    Saturn: ['Worship Shani on Saturdays', 'Donate black items to the needy', 'Serve elderly people'],
    Rahu: ['Chant Rahu Beej Mantra 108 times', 'Donate black sesame seeds on Saturdays', 'Keep silver Naga idol'],
    Ketu: ['Worship Lord Ganesha', 'Donate blankets to the poor', 'Chant Om Namah Shivaya'],
  }

  lines.push(`For ${dashaPlanet} Dasha:`)
  const pRemedies = planetRemedies[dashaPlanet] ?? ['Practice meditation and mindfulness']
  pRemedies.forEach(r => lines.push(`  • ${r}`))

  if (doshaNames.includes('Mangal Dosha')) {
    lines.push('')
    lines.push('For Mangal Dosha:')
    lines.push('  • Chant Hanuman Chalisa on Tuesdays')
    lines.push('  • Perform Mangal Shanti Puja')
  }

  return lines
}

function getPositiveHighlights(kundli: KundliData): string[] {
  const lines: string[] = []
  const exalted = kundli.planets.filter(p => p.dignity === 'Exalted')
  const ownSign = kundli.planets.filter(p => p.dignity === 'Own')

  if (exalted.length > 0) {
    lines.push(`${exalted.map(p => p.name).join(', ')} exalted — exceptional strength and blessings`)
  }
  if (ownSign.length > 0) {
    lines.push(`${ownSign.map(p => p.name).join(', ')} in own sign — natural confidence and ability`)
  }
  if (kundli.yogas.length > 0) {
    lines.push(`${kundli.yogas.length} yoga(s) detected — auspicious combinations active`)
    const strong = kundli.yogas.filter(y => y.strength === 'Excellent' || y.strength === 'Strong')
    if (strong.length > 0) {
      lines.push(`Top yoga: ${strong[0].name} — ${strong[0].description.slice(0, 60)}...`)
    }
  }

  const beneficsInKendra = kundli.planets.filter(
    p => ['Jupiter', 'Venus', 'Mercury'].includes(p.name) && [1, 4, 7, 10].includes(p.houseNumber)
  )
  if (beneficsInKendra.length > 0) {
    lines.push(`Benefics in Kendras: ${beneficsInKendra.map(p => p.name).join(', ')} — strong life support`)
  }

  if (lines.length === 0) {
    lines.push('A balanced chart with steady planetary energies')
    lines.push('Focus on your strengths and work on growth areas')
    lines.push('Regular remedies will enhance positive outcomes')
  }

  return lines
}

// ─── Canvas Video Renderer ────────────────────────────────────────────────

async function renderVideoToCanvas(
  canvas: HTMLCanvasElement,
  scenes: VideoScene[],
  onProgress: (pct: number) => void,
  onSceneChange: (idx: number) => void
): Promise<Blob> {
  const ctx = canvas.getContext('2d')!
  const W = canvas.width
  const H = canvas.height
  const FPS = 30
  const totalFrames = scenes.reduce((s, sc) => s + sc.duration * FPS, 0)

  // Use MediaRecorder to capture canvas as video
  const stream = canvas.captureStream(FPS)
  const chunks: Blob[] = []

  const mimeType = MediaRecorder.isTypeSupported('video/webm;codecs=vp9')
    ? 'video/webm;codecs=vp9'
    : MediaRecorder.isTypeSupported('video/webm')
    ? 'video/webm'
    : 'video/mp4'

  const recorder = new MediaRecorder(stream, { mimeType, videoBitsPerSecond: 2_000_000 })
  recorder.ondataavailable = (e) => { if (e.data.size > 0) chunks.push(e.data) }

  const done = new Promise<Blob>((resolve) => {
    recorder.onstop = () => {
      resolve(new Blob(chunks, { type: mimeType }))
    }
  })

  recorder.start()

  let frameCount = 0
  let sceneStartFrame = 0

  for (let si = 0; si < scenes.length; si++) {
    const scene = scenes[si]
    const sceneFrames = scene.duration * FPS
    onSceneChange(si)

    for (let f = 0; f < sceneFrames; f++) {
      const t = f / sceneFrames // 0 to 1 within scene

      // Clear
      const grad = ctx.createLinearGradient(0, 0, W, H)
      grad.addColorStop(0, '#0a0e27')
      grad.addColorStop(0.5, '#1a1040')
      grad.addColorStop(1, '#0a0e27')
      ctx.fillStyle = grad
      ctx.fillRect(0, 0, W, H)

      // Stars
      drawStarsOnCanvas(ctx, W, H, frameCount)

      // Scene fade in/out
      const fadeIn = Math.min(t * 5, 1)
      const fadeOut = Math.min((1 - t) * 5, 1)
      const alpha = Math.min(fadeIn, fadeOut)
      ctx.globalAlpha = alpha

      // Icon
      ctx.font = '48px serif'
      ctx.textAlign = 'center'
      ctx.fillStyle = scene.color
      ctx.fillText(scene.icon, W / 2, 80)

      // Title
      ctx.font = 'bold 28px serif'
      ctx.fillStyle = scene.color
      ctx.fillText(scene.title, W / 2, 130)

      // Subtitle
      if (scene.subtitle) {
        ctx.font = '16px sans-serif'
        ctx.fillStyle = 'rgba(255,255,255,0.5)'
        ctx.fillText(scene.subtitle, W / 2, 158)
      }

      // Content lines (animated reveal)
      ctx.font = '14px sans-serif'
      ctx.textAlign = 'left'
      const lineStart = 195
      const lineHeight = 22
      const revealedLines = Math.floor(t * scene.lines.length * 2)

      scene.lines.forEach((line, li) => {
        if (li > revealedLines) return
        const lineAlpha = Math.min((revealedLines - li) * 0.5, 1) * alpha
        ctx.fillStyle = `rgba(255,255,255,${lineAlpha * 0.8})`
        // Word wrap
        const maxWidth = W - 80
        const words = line.split(' ')
        let currentLine = ''
        let y = lineStart + li * lineHeight

        for (const word of words) {
          const testLine = currentLine ? `${currentLine} ${word}` : word
          if (ctx.measureText(testLine).width > maxWidth && currentLine) {
            ctx.fillText(currentLine, 40, y)
            currentLine = word
            y += lineHeight
          } else {
            currentLine = testLine
          }
        }
        if (currentLine) ctx.fillText(currentLine, 40, y)
      })

      // Progress bar at bottom
      ctx.globalAlpha = 0.3
      ctx.fillStyle = '#333'
      ctx.fillRect(20, H - 30, W - 40, 4)
      ctx.fillStyle = scene.color
      ctx.globalAlpha = 0.8
      ctx.fillRect(20, H - 30, (W - 40) * (frameCount / totalFrames), 4)

      // Branding
      ctx.globalAlpha = 0.3
      ctx.fillStyle = '#FFB347'
      ctx.font = '10px sans-serif'
      ctx.textAlign = 'center'
      ctx.fillText('Nakshatra · Vedic Astrology App', W / 2, H - 10)

      ctx.globalAlpha = 1
      frameCount++
      onProgress(frameCount / totalFrames)

      // Yield to browser to keep UI responsive
      if (f % 3 === 0) {
        await new Promise(r => setTimeout(r, 0))
      }
    }
    sceneStartFrame += sceneFrames
  }

  recorder.stop()
  return done
}

function drawStarsOnCanvas(ctx: CanvasRenderingContext2D, w: number, h: number, frame: number) {
  const rng = (seed: number) => {
    let s = seed
    return () => { s = (s * 16807) % 2147483647; return s / 2147483647 }
  }
  const rand = rng(42)
  ctx.fillStyle = 'rgba(255,255,255,0.3)'
  for (let i = 0; i < 40; i++) {
    const x = rand() * w
    const y = rand() * h
    const r = rand() * 1.2
    const twinkle = Math.sin(frame * 0.05 + i) * 0.5 + 0.5
    ctx.globalAlpha = twinkle * 0.4
    ctx.beginPath()
    ctx.arc(x, y, r, 0, Math.PI * 2)
    ctx.fill()
  }
  ctx.globalAlpha = 1
}

// ─── Sharing Utilities ────────────────────────────────────────────────────

async function shareViaWhatsApp(blob: Blob, name: string) {
  const file = new File([blob], `${name}-kundli-analysis.webm`, { type: blob.type })
  if (typeof navigator.canShare === 'function' && navigator.canShare({ files: [file] })) {
    await navigator.share({
      title: `${name}'s Kundli Analysis`,
      text: 'Watch my Vedic birth chart analysis from Nakshatra App',
      files: [file],
    })
  } else {
    // Fallback: download
    downloadBlob(blob, `${name}-kundli-analysis.webm`)
  }
}

async function shareViaEmail(blob: Blob, name: string) {
  // Cannot attach files via mailto, so download + open mailto
  downloadBlob(blob, `${name}-kundli-analysis.webm`)
  const subject = encodeURIComponent(`${name}'s Vedic Kundli Analysis`)
  const body = encodeURIComponent(`Hi,\n\nPlease find my Vedic birth chart analysis attached.\n\nGenerated by Nakshatra App - bitsizegyaan.com`)
  window.open(`mailto:?subject=${subject}&body=${body}`, '_blank')
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// ─── Preview Player ───────────────────────────────────────────────────────

function VideoPreview({ scenes, currentScene }: { scenes: VideoScene[]; currentScene: number }) {
  const scene = scenes[currentScene]
  if (!scene) return null

  return (
    <div className="aspect-video bg-cosmos rounded-xl border border-stardust/30 overflow-hidden relative">
      <div className="absolute inset-0 flex flex-col items-center justify-center p-6 text-center">
        <motion.div
          key={currentScene}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -20 }}
          className="space-y-3"
        >
          <span className="text-4xl">{scene.icon}</span>
          <h3 className="font-cinzel text-lg" style={{ color: scene.color }}>{scene.title}</h3>
          {scene.subtitle && <p className="text-xs text-white/40 font-cormorant">{scene.subtitle}</p>}
          <div className="text-left max-w-sm mx-auto">
            {scene.lines.slice(0, 4).map((line, i) => (
              <motion.p
                key={i}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.15 }}
                className="text-xs text-white/60 font-cormorant leading-relaxed"
              >{line}</motion.p>
            ))}
            {scene.lines.length > 4 && <p className="text-xs text-white/30 font-cormorant">...</p>}
          </div>
        </motion.div>
      </div>

      {/* Scene progress dots */}
      <div className="absolute bottom-3 left-0 right-0 flex justify-center gap-1">
        {scenes.map((_, i) => (
          <div key={i} className={`w-1.5 h-1.5 rounded-full transition-all ${i === currentScene ? 'bg-gold' : i < currentScene ? 'bg-gold/30' : 'bg-white/10'}`} />
        ))}
      </div>
    </div>
  )
}

// ─── Main Page ────────────────────────────────────────────────────────────

export default function VideoAnalysisPage() {
  const { kundlis, getActiveKundli, addXP } = useStore()
  const { isPremium } = usePremium()
  const activeKundli = getActiveKundli()
  const kundli = activeKundli ?? kundlis[0] ?? null

  const [generating, setGenerating] = useState(false)
  const [progress, setProgress] = useState(0)
  const [currentScene, setCurrentScene] = useState(0)
  const [videoBlob, setVideoBlob] = useState<Blob | null>(null)
  const [videoUrl, setVideoUrl] = useState<string | null>(null)
  const [previewScene, setPreviewScene] = useState(0)
  const canvasRef = useRef<HTMLCanvasElement>(null)

  const scenes = kundli ? generateScenes(kundli) : []
  const totalDuration = scenes.reduce((s, sc) => s + sc.duration, 0)

  // Auto-advance preview scenes
  useEffect(() => {
    if (generating || videoBlob || scenes.length === 0) return
    const interval = setInterval(() => {
      setPreviewScene(prev => (prev + 1) % scenes.length)
    }, 3000)
    return () => clearInterval(interval)
  }, [generating, videoBlob, scenes.length])

  const handleGenerate = useCallback(async () => {
    if (!kundli || !canvasRef.current) return
    setGenerating(true)
    setProgress(0)
    setVideoBlob(null)
    setVideoUrl(null)

    try {
      const blob = await renderVideoToCanvas(
        canvasRef.current,
        scenes,
        (pct) => setProgress(pct),
        (idx) => setCurrentScene(idx)
      )
      setVideoBlob(blob)
      const url = URL.createObjectURL(blob)
      setVideoUrl(url)
      addXP(100, 'VIDEO_ANALYSIS')
    } catch (err) {
      console.error('Video generation failed:', err)
    } finally {
      setGenerating(false)
    }
  }, [kundli, scenes, addXP])

  if (!kundli) {
    return (
      <div className="min-h-screen p-4 max-w-2xl mx-auto pb-20">
        <div className="flex items-center gap-3 mb-6">
          <Link to="/dashboard" className="p-2 rounded-full hover:bg-white/10"><ArrowLeft size={20} className="text-white/60" /></Link>
          <h1 className="text-2xl font-cinzel text-white">Video Kundli Analysis</h1>
        </div>
        <div className="glass-card p-8 text-center space-y-4">
          <div className="text-5xl">🎬</div>
          <h2 className="font-cinzel text-xl text-gold">Generate Your Kundli First</h2>
          <p className="font-cormorant text-slate-400">Create a Kundli chart to get your personalized video analysis.</p>
          <Link to="/kundli" className="inline-flex items-center gap-2 bg-gradient-to-r from-saffron to-gold text-cosmos font-cinzel font-bold px-6 py-3 rounded-xl hover:opacity-90">
            <Star size={16} /> Create Kundli <ChevronRight size={16} />
          </Link>
        </div>
      </div>
    )
  }

  const videoContent = (
    <div className="space-y-6">
      {/* Preview / Player */}
      <div className="glass-card p-4">
        {videoUrl ? (
          <div className="space-y-3">
            <video
              src={videoUrl}
              controls
              autoPlay
              className="w-full aspect-video rounded-xl bg-cosmos"
              style={{ maxHeight: 400 }}
            />
            <div className="flex items-center justify-between text-xs text-slate-400 font-cormorant">
              <span>{Math.round(totalDuration)}s · {scenes.length} scenes</span>
              <span>{videoBlob ? `${(videoBlob.size / 1024 / 1024).toFixed(1)} MB` : ''}</span>
            </div>
          </div>
        ) : generating ? (
          <div className="aspect-video bg-cosmos rounded-xl border border-stardust/30 flex flex-col items-center justify-center space-y-4">
            <Loader2 size={32} className="text-gold animate-spin" />
            <div className="text-center">
              <p className="font-cinzel text-sm text-gold">Generating Video...</p>
              <p className="font-cormorant text-xs text-slate-400">Scene {currentScene + 1} of {scenes.length}</p>
            </div>
            <div className="w-48 h-2 bg-stardust/30 rounded-full overflow-hidden">
              <motion.div
                className="h-full bg-gold rounded-full"
                animate={{ width: `${progress * 100}%` }}
              />
            </div>
            <p className="text-xs text-slate-500 font-cormorant">{Math.round(progress * 100)}%</p>
          </div>
        ) : (
          <VideoPreview scenes={scenes} currentScene={previewScene} />
        )}
      </div>

      {/* Scene Outline */}
      <div className="glass-card p-4">
        <h3 className="font-cinzel text-sm text-gold/60 uppercase tracking-wider mb-3">Video Contents ({Math.round(totalDuration)}s)</h3>
        <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">
          {scenes.map((scene, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.05 }}
              className={`p-2 rounded-lg border text-center cursor-pointer transition-all ${
                (generating && i === currentScene) || (!generating && !videoUrl && i === previewScene)
                  ? 'border-gold/40 bg-gold/10'
                  : 'border-stardust/20 bg-stardust/5 hover:bg-stardust/10'
              }`}
              onClick={() => !generating && !videoUrl && setPreviewScene(i)}
            >
              <span className="text-lg">{scene.icon}</span>
              <p className="text-[10px] font-cinzel text-white/60 mt-1 leading-tight">{scene.title}</p>
              <p className="text-[9px] text-slate-500">{scene.duration}s</p>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Actions */}
      <div className="space-y-3">
        {!videoUrl ? (
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-saffron to-gold text-cosmos font-cinzel font-bold py-4 rounded-xl hover:opacity-90 active:scale-95 transition-all disabled:opacity-50"
          >
            {generating ? (
              <><Loader2 size={18} className="animate-spin" /> Rendering {Math.round(progress * 100)}%...</>
            ) : (
              <><Play size={18} /> Generate Video Analysis</>
            )}
          </button>
        ) : (
          <div className="grid grid-cols-3 gap-3">
            <button
              onClick={() => videoBlob && downloadBlob(videoBlob, `${kundli.name}-kundli-analysis.webm`)}
              className="flex flex-col items-center gap-2 p-4 rounded-xl border border-stardust/30 bg-stardust/5 hover:bg-stardust/10 transition-all"
            >
              <Download size={20} className="text-gold" />
              <span className="text-xs font-cinzel text-slate-300">Download</span>
            </button>
            <button
              onClick={() => videoBlob && shareViaWhatsApp(videoBlob, kundli.name)}
              className="flex flex-col items-center gap-2 p-4 rounded-xl border border-green-500/30 bg-green-500/5 hover:bg-green-500/10 transition-all"
            >
              <MessageCircle size={20} className="text-green-400" />
              <span className="text-xs font-cinzel text-slate-300">WhatsApp</span>
            </button>
            <button
              onClick={() => videoBlob && shareViaEmail(videoBlob, kundli.name)}
              className="flex flex-col items-center gap-2 p-4 rounded-xl border border-blue-500/30 bg-blue-500/5 hover:bg-blue-500/10 transition-all"
            >
              <Mail size={20} className="text-blue-400" />
              <span className="text-xs font-cinzel text-slate-300">Email</span>
            </button>
          </div>
        )}

        {videoUrl && (
          <button
            onClick={() => { setVideoBlob(null); setVideoUrl(null); setProgress(0) }}
            className="w-full text-xs font-cinzel text-slate-400 hover:text-slate-200 py-2 transition-colors"
          >
            Regenerate Video
          </button>
        )}
      </div>
    </div>
  )

  return (
    <div className="min-h-screen p-4 max-w-2xl mx-auto pb-20">
      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <Link to="/dashboard" className="p-2 rounded-full hover:bg-white/10">
          <ArrowLeft size={20} className="text-white/60" />
        </Link>
        <div>
          <h1 className="text-2xl font-cinzel text-white">Video Analysis</h1>
          <p className="text-sm text-white/40 font-cormorant">{kundli.name}'s Kundli · {Math.round(totalDuration)}s video</p>
        </div>
        <div className="ml-auto flex items-center gap-1 text-xs font-cinzel text-purple-300 bg-purple-500/10 border border-purple-500/20 px-2 py-1 rounded-full">
          <Sparkles size={10} /> Premium
        </div>
      </div>

      {/* Feature highlights for non-premium */}
      {!isPremium && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="glass-card p-5 mb-6 border border-purple-500/20"
        >
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-full bg-purple-500/10 border border-purple-500/30 flex items-center justify-center">
              <Lock size={18} className="text-purple-400" />
            </div>
            <div>
              <h3 className="font-cinzel text-sm text-purple-300">Premium Feature</h3>
              <p className="text-xs font-cormorant text-slate-400">Generate a shareable video analysis of your Kundli</p>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-2 text-xs font-cormorant text-slate-400">
            <div className="flex items-center gap-1.5"><Star size={10} className="text-gold" /> Birth chart overview</div>
            <div className="flex items-center gap-1.5"><Clock size={10} className="text-cyan-400" /> Dasha predictions</div>
            <div className="flex items-center gap-1.5"><TrendingUp size={10} className="text-green-400" /> Weekly & monthly forecast</div>
            <div className="flex items-center gap-1.5"><Shield size={10} className="text-red-400" /> Remedies & rituals</div>
            <div className="flex items-center gap-1.5"><MessageCircle size={10} className="text-green-400" /> Share via WhatsApp</div>
            <div className="flex items-center gap-1.5"><Mail size={10} className="text-blue-400" /> Send via email</div>
          </div>
        </motion.div>
      )}

      {/* Premium Gate wraps the video content */}
      <PremiumGate feature="video_analysis" featureName="Video Kundli Analysis" requiredPlan="guru">
        {videoContent}
      </PremiumGate>

      {/* Hidden canvas for video rendering */}
      <canvas ref={canvasRef} width={640} height={480} className="hidden" />

      <div className="mt-6 p-3 rounded-xl bg-purple-500/5 border border-purple-500/20 text-center">
        <p className="text-xs font-cormorant text-slate-400">
          Video is generated entirely on your device. No data is sent to any server.
          Share securely via WhatsApp or email.
        </p>
      </div>
    </div>
  )
}
