// ─── Lucide React Icon Barrel ────────────────────────────────────────────────
// Imports icons directly from their individual ESM files, bypassing the main
// lucide-react barrel (index.mjs) which re-exports all 3248 icons.
//
// WHY: lucide-react's barrel triggers Rollup to open every individual icon
// file during tree-shaking analysis. On macOS the default fd limit (1024)
// causes the build to deadlock. Direct imports prevent this — only the 58
// files we actually use are opened.
//
// Usage: import { Star, Home } from '@/lib/lucide-icons'
// To add a new icon: add the export line and run the build.

export { default as Activity } from 'lucide-react/dist/esm/icons/activity.js'
export { default as AlertCircle } from 'lucide-react/dist/esm/icons/alert-circle.js'
export { default as AlertTriangle } from 'lucide-react/dist/esm/icons/alert-triangle.js'
export { default as ArrowLeft } from 'lucide-react/dist/esm/icons/arrow-left.js'
export { default as AtSign } from 'lucide-react/dist/esm/icons/at-sign.js'
export { default as Award } from 'lucide-react/dist/esm/icons/award.js'
export { default as BarChart3 } from 'lucide-react/dist/esm/icons/bar-chart-3.js'
export { default as Bell } from 'lucide-react/dist/esm/icons/bell.js'
export { default as BookOpen } from 'lucide-react/dist/esm/icons/book-open.js'
export { default as Bookmark } from 'lucide-react/dist/esm/icons/bookmark.js'
export { default as Brain } from 'lucide-react/dist/esm/icons/brain.js'
export { default as Briefcase } from 'lucide-react/dist/esm/icons/briefcase.js'
export { default as Building2 } from 'lucide-react/dist/esm/icons/building-2.js'
export { default as Calculator } from 'lucide-react/dist/esm/icons/calculator.js'
export { default as Calendar } from 'lucide-react/dist/esm/icons/calendar.js'
export { default as Check } from 'lucide-react/dist/esm/icons/check.js'
export { default as CheckCircle } from 'lucide-react/dist/esm/icons/check-circle.js'
export { default as CheckCircle2 } from 'lucide-react/dist/esm/icons/check-circle-2.js'
export { default as ChevronDown } from 'lucide-react/dist/esm/icons/chevron-down.js'
export { default as ChevronLeft } from 'lucide-react/dist/esm/icons/chevron-left.js'
export { default as ChevronRight } from 'lucide-react/dist/esm/icons/chevron-right.js'
export { default as ChevronUp } from 'lucide-react/dist/esm/icons/chevron-up.js'
export { default as Circle } from 'lucide-react/dist/esm/icons/circle.js'
export { default as Clock } from 'lucide-react/dist/esm/icons/clock.js'
export { default as Compass } from 'lucide-react/dist/esm/icons/compass.js'
export { default as Copy } from 'lucide-react/dist/esm/icons/copy.js'
export { default as CreditCard } from 'lucide-react/dist/esm/icons/credit-card.js'
export { default as Crown } from 'lucide-react/dist/esm/icons/crown.js'
export { default as Database } from 'lucide-react/dist/esm/icons/database.js'
export { default as Download } from 'lucide-react/dist/esm/icons/download.js'
export { default as Droplets } from 'lucide-react/dist/esm/icons/droplets.js'
export { default as Edit3 } from 'lucide-react/dist/esm/icons/edit-3.js'
export { default as ExternalLink } from 'lucide-react/dist/esm/icons/external-link.js'
export { default as Eye } from 'lucide-react/dist/esm/icons/eye.js'
export { default as EyeOff } from 'lucide-react/dist/esm/icons/eye-off.js'
export { default as FileText } from 'lucide-react/dist/esm/icons/file-text.js'
export { default as Filter } from 'lucide-react/dist/esm/icons/filter.js'
export { default as Flame } from 'lucide-react/dist/esm/icons/flame.js'
export { default as Gem } from 'lucide-react/dist/esm/icons/gem.js'
export { default as Globe } from 'lucide-react/dist/esm/icons/globe.js'
export { default as Grid3X3 } from 'lucide-react/dist/esm/icons/grid-3x3.js'
export { default as Hash } from 'lucide-react/dist/esm/icons/hash.js'
export { default as Heart } from 'lucide-react/dist/esm/icons/heart.js'
export { default as Home } from 'lucide-react/dist/esm/icons/home.js'
export { default as Info } from 'lucide-react/dist/esm/icons/info.js'
export { default as Layers } from 'lucide-react/dist/esm/icons/layers.js'
export { default as Leaf } from 'lucide-react/dist/esm/icons/leaf.js'
export { default as Link2 } from 'lucide-react/dist/esm/icons/link-2.js'
export { default as List } from 'lucide-react/dist/esm/icons/list.js'
export { default as Loader2 } from 'lucide-react/dist/esm/icons/loader-2.js'
export { default as Lock } from 'lucide-react/dist/esm/icons/lock.js'
export { default as LogIn } from 'lucide-react/dist/esm/icons/log-in.js'
export { default as LogOut } from 'lucide-react/dist/esm/icons/log-out.js'
export { default as Mail } from 'lucide-react/dist/esm/icons/mail.js'
export { default as Map } from 'lucide-react/dist/esm/icons/map.js'
export { default as MapPin } from 'lucide-react/dist/esm/icons/map-pin.js'
export { default as Menu } from 'lucide-react/dist/esm/icons/menu.js'
export { default as MessageCircle } from 'lucide-react/dist/esm/icons/message-circle.js'
export { default as Moon } from 'lucide-react/dist/esm/icons/moon.js'
export { default as Mountain } from 'lucide-react/dist/esm/icons/mountain.js'
export { default as Plane } from 'lucide-react/dist/esm/icons/plane.js'
export { default as Play } from 'lucide-react/dist/esm/icons/play.js'
export { default as Plus } from 'lucide-react/dist/esm/icons/plus.js'
export { default as RefreshCw } from 'lucide-react/dist/esm/icons/refresh-cw.js'
export { default as RotateCcw } from 'lucide-react/dist/esm/icons/rotate-ccw.js'
export { default as ScrollText } from 'lucide-react/dist/esm/icons/scroll-text.js'
export { default as Search } from 'lucide-react/dist/esm/icons/search.js'
export { default as Send } from 'lucide-react/dist/esm/icons/send.js'
export { default as Settings } from 'lucide-react/dist/esm/icons/settings.js'
export { default as Share2 } from 'lucide-react/dist/esm/icons/share-2.js'
export { default as Shield } from 'lucide-react/dist/esm/icons/shield.js'
export { default as Smartphone } from 'lucide-react/dist/esm/icons/smartphone.js'
export { default as Sparkles } from 'lucide-react/dist/esm/icons/sparkles.js'
export { default as Star } from 'lucide-react/dist/esm/icons/star.js'
export { default as Sun } from 'lucide-react/dist/esm/icons/sun.js'
export { default as Target } from 'lucide-react/dist/esm/icons/target.js'
export { default as Telescope } from 'lucide-react/dist/esm/icons/telescope.js'
export { default as Trash2 } from 'lucide-react/dist/esm/icons/trash-2.js'
export { default as TrendingUp } from 'lucide-react/dist/esm/icons/trending-up.js'
export { default as Trophy } from 'lucide-react/dist/esm/icons/trophy.js'
export { default as Upload } from 'lucide-react/dist/esm/icons/upload.js'
export { default as User } from 'lucide-react/dist/esm/icons/user.js'
export { default as UserPlus } from 'lucide-react/dist/esm/icons/user-plus.js'
export { default as Users } from 'lucide-react/dist/esm/icons/users.js'
export { default as Wind } from 'lucide-react/dist/esm/icons/wind.js'
export { default as X } from 'lucide-react/dist/esm/icons/x.js'
export { default as XCircle } from 'lucide-react/dist/esm/icons/x-circle.js'
export { default as Zap } from 'lucide-react/dist/esm/icons/zap.js'
