// ============================================================
// Vedic Astrology Quiz Data
// 100+ questions across 6 categories with difficulty levels.
// ============================================================

export type QuizCategory = 'basics' | 'nakshatras' | 'rashis' | 'planets' | 'houses' | 'yogas'
export type QuizDifficulty = 'easy' | 'medium' | 'hard'

export interface QuizQuestion {
  id: string
  category: QuizCategory
  difficulty: QuizDifficulty
  question: string
  options: [string, string, string, string]
  correctIndex: number
  explanation: string
  xpReward: number
}

const XP = { easy: 10, medium: 25, hard: 50 }

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // ── Basics (20) ────────────────────────────────────────────────────────────
  { id: 'b1', category: 'basics', difficulty: 'easy', question: 'How many Nakshatras are there in Vedic astrology?', options: ['12', '27', '9', '108'], correctIndex: 1, explanation: 'There are 27 Nakshatras (lunar mansions), each spanning 13\u00B020\' of the zodiac.', xpReward: XP.easy },
  { id: 'b2', category: 'basics', difficulty: 'easy', question: 'Which planet rules Tuesday?', options: ['Mercury', 'Jupiter', 'Mars', 'Venus'], correctIndex: 2, explanation: 'Tuesday (Mangalvar) is ruled by Mars (Mangal), the planet of energy and courage.', xpReward: XP.easy },
  { id: 'b3', category: 'basics', difficulty: 'easy', question: 'What is the Vedic term for a birth chart?', options: ['Kundli', 'Mantra', 'Yantra', 'Tantra'], correctIndex: 0, explanation: 'A Kundli (also called Janam Patri) is the Vedic birth chart showing planetary positions at birth.', xpReward: XP.easy },
  { id: 'b4', category: 'basics', difficulty: 'easy', question: 'How many Rashis (zodiac signs) are there?', options: ['9', '12', '27', '7'], correctIndex: 1, explanation: 'There are 12 Rashis, each spanning 30 degrees of the 360-degree zodiac.', xpReward: XP.easy },
  { id: 'b5', category: 'basics', difficulty: 'easy', question: 'What does "Graha" mean in Sanskrit?', options: ['Star', 'Planet/Seizer', 'House', 'Sign'], correctIndex: 1, explanation: 'Graha literally means "seizer" or "that which grasps." It refers to celestial bodies that influence life.', xpReward: XP.easy },
  { id: 'b6', category: 'basics', difficulty: 'medium', question: 'What is the Ayanamsa?', options: ['Moon phase', 'Precession correction angle', 'House division', 'Planetary aspect'], correctIndex: 1, explanation: 'Ayanamsa is the angular difference between tropical and sidereal zodiacs due to precession of equinoxes.', xpReward: XP.medium },
  { id: 'b7', category: 'basics', difficulty: 'medium', question: 'Which Veda contains the origins of Jyotish Shastra?', options: ['Rig Veda', 'Sama Veda', 'Atharva Veda', 'Yajur Veda'], correctIndex: 0, explanation: 'Jyotish is a Vedanga (limb of Veda) originating from the Rig Veda, the oldest sacred text.', xpReward: XP.medium },
  { id: 'b8', category: 'basics', difficulty: 'medium', question: 'What are the Navagrahas?', options: ['9 planets', '9 gems', '9 houses', '9 yogas'], correctIndex: 0, explanation: 'Navagrahas are the 9 celestial bodies: Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, Ketu.', xpReward: XP.medium },
  { id: 'b9', category: 'basics', difficulty: 'medium', question: 'What is a "Hora" in Vedic astrology?', options: ['A type of yoga', 'A planetary hour', 'A lunar month', 'A zodiac degree'], correctIndex: 1, explanation: 'Hora is a planetary hour — each hour of the day is ruled by a different planet in sequence.', xpReward: XP.medium },
  { id: 'b10', category: 'basics', difficulty: 'hard', question: 'What is the total duration of the Vimshottari Dasha system?', options: ['100 years', '108 years', '120 years', '144 years'], correctIndex: 2, explanation: 'The Vimshottari Dasha system spans 120 years, divided among 9 planets in fixed proportions.', xpReward: XP.hard },
  { id: 'b11', category: 'basics', difficulty: 'easy', question: 'Which day of the week is ruled by Jupiter?', options: ['Monday', 'Wednesday', 'Thursday', 'Friday'], correctIndex: 2, explanation: 'Thursday (Guruvar) is ruled by Jupiter (Guru/Brihaspati), the planet of wisdom.', xpReward: XP.easy },
  { id: 'b12', category: 'basics', difficulty: 'easy', question: 'What element is Aries (Mesha)?', options: ['Water', 'Earth', 'Fire', 'Air'], correctIndex: 2, explanation: 'Mesha (Aries) is a Fire sign, along with Simha (Leo) and Dhanu (Sagittarius).', xpReward: XP.easy },
  { id: 'b13', category: 'basics', difficulty: 'medium', question: 'What is the significance of the Ascendant (Lagna)?', options: ['Moon sign', 'Rising sign at birth', 'Strongest planet', 'Birth nakshatra'], correctIndex: 1, explanation: 'The Lagna/Ascendant is the zodiac sign rising on the eastern horizon at the moment of birth.', xpReward: XP.medium },
  { id: 'b14', category: 'basics', difficulty: 'hard', question: 'What is "Shadbala"?', options: ['Six strengths of planets', 'Six types of yogas', 'Six lunar phases', 'Six house divisions'], correctIndex: 0, explanation: 'Shadbala measures planetary strength through 6 criteria: positional, directional, temporal, motional, natural, and aspectual.', xpReward: XP.hard },
  { id: 'b15', category: 'basics', difficulty: 'easy', question: 'What does "Jyotish" literally mean?', options: ['Star reading', 'Light/Science of light', 'Moon science', 'Fate reading'], correctIndex: 1, explanation: 'Jyotish comes from "Jyoti" (light) and means "Science of Light" or "Lord of Light."', xpReward: XP.easy },

  // ── Nakshatras (20) ────────────────────────────────────────────────────────
  { id: 'n1', category: 'nakshatras', difficulty: 'easy', question: 'Which is the first Nakshatra in the zodiac?', options: ['Bharani', 'Rohini', 'Ashwini', 'Krittika'], correctIndex: 2, explanation: 'Ashwini is the first Nakshatra, starting at 0\u00B0 Aries. It is ruled by Ketu.', xpReward: XP.easy },
  { id: 'n2', category: 'nakshatras', difficulty: 'easy', question: 'Which planet rules Ashwini Nakshatra?', options: ['Sun', 'Ketu', 'Venus', 'Mars'], correctIndex: 1, explanation: 'Ashwini is ruled by Ketu. Its deity is the Ashwini Kumaras (celestial physicians).', xpReward: XP.easy },
  { id: 'n3', category: 'nakshatras', difficulty: 'medium', question: 'Which Nakshatra is considered the "Star of the Moon"?', options: ['Pushya', 'Rohini', 'Hasta', 'Shravana'], correctIndex: 1, explanation: 'Rohini is the Moon\'s favorite Nakshatra. The Moon is exalted in Taurus where Rohini resides.', xpReward: XP.medium },
  { id: 'n4', category: 'nakshatras', difficulty: 'medium', question: 'What is the Nakshatra Pada?', options: ['Nakshatra lord', 'Quarter division of nakshatra', 'Nakshatra deity', 'Nakshatra element'], correctIndex: 1, explanation: 'Each Nakshatra is divided into 4 Padas (quarters) of 3\u00B020\' each. Each Pada maps to a navamsha sign.', xpReward: XP.medium },
  { id: 'n5', category: 'nakshatras', difficulty: 'hard', question: 'Which Nakshatra is associated with the deity Yama (god of death)?', options: ['Bharani', 'Ashlesha', 'Jyeshtha', 'Mula'], correctIndex: 0, explanation: 'Bharani is ruled by Venus but its deity is Yama, representing transformation and the cycle of birth/death.', xpReward: XP.hard },
  { id: 'n6', category: 'nakshatras', difficulty: 'easy', question: 'How many Padas does each Nakshatra have?', options: ['2', '3', '4', '9'], correctIndex: 2, explanation: 'Each Nakshatra has 4 Padas, giving 108 total Padas (27 x 4) across the zodiac.', xpReward: XP.easy },
  { id: 'n7', category: 'nakshatras', difficulty: 'medium', question: 'Which Nakshatra is known as the "Star of Transformation"?', options: ['Mula', 'Ardra', 'Ashlesha', 'Vishakha'], correctIndex: 0, explanation: 'Mula (root) is ruled by Ketu and represents uprooting and fundamental transformation.', xpReward: XP.medium },
  { id: 'n8', category: 'nakshatras', difficulty: 'hard', question: 'What is the Gana of Ashwini Nakshatra?', options: ['Rakshasa', 'Manushya', 'Deva', 'Mixed'], correctIndex: 2, explanation: 'Ashwini belongs to Deva Gana (divine temperament). Gana is used in marriage compatibility.', xpReward: XP.hard },
  { id: 'n9', category: 'nakshatras', difficulty: 'easy', question: 'Which Nakshatra is ruled by the Sun?', options: ['Krittika', 'Magha', 'Uttara Phalguni', 'All of these'], correctIndex: 3, explanation: 'Sun rules 3 Nakshatras: Krittika, Uttara Phalguni, and Uttara Ashadha (Vimshottari cycle).', xpReward: XP.easy },
  { id: 'n10', category: 'nakshatras', difficulty: 'medium', question: 'Pushya is considered the most auspicious Nakshatra for which activity?', options: ['Marriage', 'Starting a business', 'Almost everything', 'Warfare'], correctIndex: 2, explanation: 'Pushya (ruled by Saturn, deity Brihaspati) is considered the most auspicious Nakshatra for nearly all activities.', xpReward: XP.medium },

  // ── Rashis (15) ────────────────────────────────────────────────────────────
  { id: 'r1', category: 'rashis', difficulty: 'easy', question: 'What is the Vedic name for Leo?', options: ['Karka', 'Simha', 'Kanya', 'Tula'], correctIndex: 1, explanation: 'Leo is called Simha in Vedic astrology, ruled by the Sun.', xpReward: XP.easy },
  { id: 'r2', category: 'rashis', difficulty: 'easy', question: 'Which planet rules Scorpio (Vrischika)?', options: ['Saturn', 'Venus', 'Mars', 'Ketu'], correctIndex: 2, explanation: 'Vrischika (Scorpio) is ruled by Mars, the planet of intensity and transformation.', xpReward: XP.easy },
  { id: 'r3', category: 'rashis', difficulty: 'easy', question: 'What is Kumbha in Western astrology?', options: ['Capricorn', 'Aquarius', 'Pisces', 'Sagittarius'], correctIndex: 1, explanation: 'Kumbha is Aquarius, ruled by Saturn. The symbol is the water bearer.', xpReward: XP.easy },
  { id: 'r4', category: 'rashis', difficulty: 'medium', question: 'Which Rashi is symbolized by the Scales?', options: ['Kanya', 'Tula', 'Mithuna', 'Dhanu'], correctIndex: 1, explanation: 'Tula (Libra) is symbolized by the Scales, ruled by Venus.', xpReward: XP.medium },
  { id: 'r5', category: 'rashis', difficulty: 'medium', question: 'Saturn rules which two Rashis?', options: ['Makara & Kumbha', 'Mesha & Vrischika', 'Mithuna & Kanya', 'Karka & Simha'], correctIndex: 0, explanation: 'Saturn rules Makara (Capricorn) and Kumbha (Aquarius).', xpReward: XP.medium },
  { id: 'r6', category: 'rashis', difficulty: 'medium', question: 'In which Rashi is the Moon exalted?', options: ['Karka', 'Vrishabha', 'Meena', 'Simha'], correctIndex: 1, explanation: 'The Moon is exalted in Vrishabha (Taurus) at 3 degrees, specifically in Rohini Nakshatra.', xpReward: XP.medium },
  { id: 'r7', category: 'rashis', difficulty: 'hard', question: 'What is the Moolatrikona sign of Mars?', options: ['Mesha (0-12\u00B0)', 'Vrischika', 'Makara', 'Mesha (12-30\u00B0)'], correctIndex: 0, explanation: 'Mars has its Moolatrikona in the first 12 degrees of Mesha (Aries).', xpReward: XP.hard },
  { id: 'r8', category: 'rashis', difficulty: 'easy', question: 'Which is the last sign of the zodiac?', options: ['Kumbha', 'Meena', 'Dhanu', 'Makara'], correctIndex: 1, explanation: 'Meena (Pisces) is the 12th and last sign, ruled by Jupiter, representing spiritual completion.', xpReward: XP.easy },
  { id: 'r9', category: 'rashis', difficulty: 'hard', question: 'Which sign is called the "debilitation" sign of Jupiter?', options: ['Makara', 'Vrischika', 'Kanya', 'Mesha'], correctIndex: 0, explanation: 'Jupiter is debilitated in Makara (Capricorn). It is exalted in Karka (Cancer).', xpReward: XP.hard },
  { id: 'r10', category: 'rashis', difficulty: 'medium', question: 'How many Water signs are there?', options: ['2', '3', '4', '1'], correctIndex: 1, explanation: 'Three Water signs: Karka (Cancer), Vrischika (Scorpio), and Meena (Pisces).', xpReward: XP.medium },

  // ── Planets (15) ──────────────────────────────────────────────────────────
  { id: 'p1', category: 'planets', difficulty: 'easy', question: 'Which planet is known as "Guru" in Vedic astrology?', options: ['Saturn', 'Jupiter', 'Venus', 'Mercury'], correctIndex: 1, explanation: 'Jupiter is called Guru (teacher) or Brihaspati, the celestial preceptor of the gods.', xpReward: XP.easy },
  { id: 'p2', category: 'planets', difficulty: 'easy', question: 'Rahu and Ketu are known as what type of planets?', options: ['Inner planets', 'Shadow planets', 'Gas giants', 'Benefic planets'], correctIndex: 1, explanation: 'Rahu and Ketu are Chaya Grahas (shadow planets) — the north and south lunar nodes.', xpReward: XP.easy },
  { id: 'p3', category: 'planets', difficulty: 'medium', question: 'What is the Maha Dasha period of Venus?', options: ['16 years', '17 years', '19 years', '20 years'], correctIndex: 3, explanation: 'Venus has the longest Maha Dasha at 20 years in the Vimshottari system.', xpReward: XP.medium },
  { id: 'p4', category: 'planets', difficulty: 'medium', question: 'Which planet is exalted in Cancer (Karka)?', options: ['Moon', 'Jupiter', 'Venus', 'Sun'], correctIndex: 1, explanation: 'Jupiter is exalted in Karka (Cancer) at 5 degrees. Moon is exalted in Taurus, not Cancer.', xpReward: XP.medium },
  { id: 'p5', category: 'planets', difficulty: 'hard', question: 'Which planet has a Dasha period of exactly 7 years?', options: ['Mercury', 'Ketu only', 'Mars only', 'Both Ketu and Mars'], correctIndex: 3, explanation: 'Both Ketu and Mars have 7-year Maha Dasha periods in the Vimshottari system.', xpReward: XP.hard },
  { id: 'p6', category: 'planets', difficulty: 'easy', question: 'Which planet governs beauty, love, and luxury?', options: ['Moon', 'Venus', 'Jupiter', 'Mercury'], correctIndex: 1, explanation: 'Venus (Shukra) governs beauty, romance, luxury, art, and material comforts.', xpReward: XP.easy },
  { id: 'p7', category: 'planets', difficulty: 'medium', question: 'Which two planets are friends with each other?', options: ['Sun & Saturn', 'Mars & Mercury', 'Jupiter & Sun', 'Venus & Mars'], correctIndex: 2, explanation: 'Jupiter and Sun are natural friends. Sun considers Jupiter a friend and vice versa.', xpReward: XP.medium },
  { id: 'p8', category: 'planets', difficulty: 'hard', question: 'What is the exact Dasha period of Saturn?', options: ['17 years', '18 years', '19 years', '20 years'], correctIndex: 2, explanation: 'Saturn has a 19-year Maha Dasha, the second longest after Venus (20 years).', xpReward: XP.hard },
  { id: 'p9', category: 'planets', difficulty: 'medium', question: 'Which planet represents communication and intellect?', options: ['Jupiter', 'Mercury', 'Sun', 'Moon'], correctIndex: 1, explanation: 'Mercury (Budha) governs communication, intellect, trade, and analytical thinking.', xpReward: XP.medium },
  { id: 'p10', category: 'planets', difficulty: 'easy', question: 'What is Sade Sati related to?', options: ['Jupiter transit', 'Saturn transit over Moon sign', 'Rahu-Ketu axis', 'Mars retrograde'], correctIndex: 1, explanation: 'Sade Sati is the 7.5-year period when Saturn transits the 12th, 1st, and 2nd houses from natal Moon.', xpReward: XP.easy },

  // ── Houses (15) ───────────────────────────────────────────────────────────
  { id: 'h1', category: 'houses', difficulty: 'easy', question: 'Which house represents marriage?', options: ['5th house', '7th house', '4th house', '10th house'], correctIndex: 1, explanation: 'The 7th house (Kalatra Bhava) represents marriage, partnerships, and spouse.', xpReward: XP.easy },
  { id: 'h2', category: 'houses', difficulty: 'easy', question: 'What does the 10th house signify?', options: ['Home', 'Children', 'Career & reputation', 'Spirituality'], correctIndex: 2, explanation: 'The 10th house (Karma Bhava) represents career, profession, public reputation, and authority.', xpReward: XP.easy },
  { id: 'h3', category: 'houses', difficulty: 'medium', question: 'Which house is called the "House of Loss"?', options: ['6th house', '8th house', '12th house', '3rd house'], correctIndex: 2, explanation: 'The 12th house (Vyaya Bhava) is the house of loss, expenses, isolation, and also liberation (moksha).', xpReward: XP.medium },
  { id: 'h4', category: 'houses', difficulty: 'medium', question: 'The Trikona (trine) houses are:', options: ['1, 4, 7, 10', '1, 5, 9', '2, 6, 10', '3, 7, 11'], correctIndex: 1, explanation: 'The Trikona houses (1st, 5th, 9th) are the most auspicious. They represent dharma, creativity, and luck.', xpReward: XP.medium },
  { id: 'h5', category: 'houses', difficulty: 'hard', question: 'Which houses form the "Dusthana" (evil houses)?', options: ['3, 6, 8, 12', '6, 8, 12', '2, 7, 12', '4, 8, 12'], correctIndex: 1, explanation: 'The Dusthana houses are 6th (enemies), 8th (death/transformation), and 12th (loss). They bring challenges.', xpReward: XP.hard },
  { id: 'h6', category: 'houses', difficulty: 'easy', question: 'Which house represents children and creativity?', options: ['2nd house', '4th house', '5th house', '7th house'], correctIndex: 2, explanation: 'The 5th house (Putra Bhava) represents children, creativity, intelligence, and romance.', xpReward: XP.easy },
  { id: 'h7', category: 'houses', difficulty: 'medium', question: 'The Kendra (angular) houses are:', options: ['1, 5, 9', '1, 4, 7, 10', '2, 5, 8, 11', '3, 6, 9, 12'], correctIndex: 1, explanation: 'The Kendra houses (1st, 4th, 7th, 10th) are pillars of the chart representing self, home, partner, and career.', xpReward: XP.medium },
  { id: 'h8', category: 'houses', difficulty: 'hard', question: 'Which house is the "Maraka" (death-inflicting) house?', options: ['8th house', '12th house', '2nd and 7th houses', '6th house'], correctIndex: 2, explanation: 'The 2nd and 7th houses are Maraka (death-inflicting) houses. Their lords can trigger health crises in specific dashas.', xpReward: XP.hard },
  { id: 'h9', category: 'houses', difficulty: 'easy', question: 'Which house represents wealth and speech?', options: ['1st house', '2nd house', '11th house', '5th house'], correctIndex: 1, explanation: 'The 2nd house (Dhana Bhava) represents wealth, speech, family, food, and stored resources.', xpReward: XP.easy },
  { id: 'h10', category: 'houses', difficulty: 'medium', question: 'The 11th house represents:', options: ['Enemies', 'Gains and desires', 'Death', 'Education'], correctIndex: 1, explanation: 'The 11th house (Labha Bhava) represents gains, income, friendships, and fulfillment of desires.', xpReward: XP.medium },

  // ── Yogas & Doshas (10) ───────────────────────────────────────────────────
  { id: 'y1', category: 'yogas', difficulty: 'medium', question: 'What forms Gajakesari Yoga?', options: ['Sun-Mars conjunction', 'Jupiter in Kendra from Moon', 'Venus-Mercury conjunction', 'Saturn-Rahu conjunction'], correctIndex: 1, explanation: 'Gajakesari Yoga is formed when Jupiter is in a Kendra (1,4,7,10) from the Moon. It gives wisdom and fame.', xpReward: XP.medium },
  { id: 'y2', category: 'yogas', difficulty: 'easy', question: 'What is Mangal Dosha?', options: ['Jupiter weakness', 'Mars in 1,2,4,7,8,12 houses', 'Saturn-Moon conjunction', 'Rahu-Ketu axis'], correctIndex: 1, explanation: 'Mangal Dosha (Kuja Dosha) occurs when Mars is in the 1st, 2nd, 4th, 7th, 8th, or 12th house from ascendant.', xpReward: XP.easy },
  { id: 'y3', category: 'yogas', difficulty: 'hard', question: 'Which houses form Kaal Sarp Dosha?', options: ['When all planets are between Rahu-Ketu', 'Mars in 8th house', 'Saturn aspecting Moon', 'Sun-Rahu conjunction'], correctIndex: 0, explanation: 'Kaal Sarp Dosha forms when all 7 planets are hemmed between the Rahu-Ketu axis.', xpReward: XP.hard },
  { id: 'y4', category: 'yogas', difficulty: 'medium', question: 'What is Budh-Aditya Yoga?', options: ['Mercury-Venus conjunction', 'Sun-Mercury conjunction', 'Jupiter-Mercury conjunction', 'Moon-Mercury conjunction'], correctIndex: 1, explanation: 'Budh-Aditya Yoga forms when Sun and Mercury conjoin. It grants intelligence and communication skills.', xpReward: XP.medium },
  { id: 'y5', category: 'yogas', difficulty: 'hard', question: 'Which yoga is formed by all planets in one house?', options: ['Sannyasa Yoga', 'Viparita Raja Yoga', 'Kemadruma Yoga', 'Graha Malika Yoga'], correctIndex: 0, explanation: 'When multiple planets combine in one sign, Sannyasa Yoga can form, indicating spiritual renunciation.', xpReward: XP.hard },
  { id: 'y6', category: 'yogas', difficulty: 'medium', question: 'Raja Yoga is formed by the conjunction of lords of which houses?', options: ['Kendra and Trikona', 'Dusthana houses', 'Upachaya houses', 'Maraka houses'], correctIndex: 0, explanation: 'Raja Yoga forms when lords of Kendra (1,4,7,10) and Trikona (1,5,9) houses combine. It brings power and success.', xpReward: XP.medium },
  { id: 'y7', category: 'yogas', difficulty: 'easy', question: 'What does "Dosha" mean in astrology?', options: ['Blessing', 'Yoga', 'Flaw or affliction', 'Strength'], correctIndex: 2, explanation: 'Dosha means flaw, blemish, or affliction. It indicates challenging planetary combinations in the chart.', xpReward: XP.easy },
  { id: 'y8', category: 'yogas', difficulty: 'hard', question: 'What is Neecha Bhanga Raja Yoga?', options: ['Debilitated planet gets cancelled', 'Two exalted planets conjoin', 'Moon in good house', 'Jupiter aspects ascendant'], correctIndex: 0, explanation: 'Neecha Bhanga Raja Yoga forms when a debilitated planet\'s weakness is cancelled by specific conditions, turning it into a powerful yoga.', xpReward: XP.hard },
  { id: 'y9', category: 'yogas', difficulty: 'medium', question: 'Kemadruma Yoga is caused by:', options: ['Strong Jupiter', 'No planet adjacent to Moon', 'Mars-Saturn conjunction', 'Venus combustion'], correctIndex: 1, explanation: 'Kemadruma Yoga occurs when no planet (except Sun, Rahu, Ketu) is in the 2nd or 12th from Moon, causing emotional difficulties.', xpReward: XP.medium },
  { id: 'y10', category: 'yogas', difficulty: 'easy', question: 'Sade Sati typically brings:', options: ['Only wealth', 'Challenges and growth through Saturn', 'Immediate luck', 'Marriage'], correctIndex: 1, explanation: 'Sade Sati brings lessons, challenges, and ultimately growth through Saturn\'s discipline over 7.5 years.', xpReward: XP.easy },
]

export const CATEGORY_INFO: Record<QuizCategory, { label: string; icon: string; color: string }> = {
  basics: { label: 'Basics', icon: '\u{1F4D6}', color: 'from-blue-500 to-cyan-500' },
  nakshatras: { label: 'Nakshatras', icon: '\u2728', color: 'from-amber-500 to-yellow-400' },
  rashis: { label: 'Rashis', icon: '\u2648', color: 'from-purple-500 to-pink-500' },
  planets: { label: 'Planets', icon: '\u{1FA90}', color: 'from-orange-500 to-red-500' },
  houses: { label: 'Houses', icon: '\u{1F3E0}', color: 'from-green-500 to-emerald-400' },
  yogas: { label: 'Yogas & Doshas', icon: '\u{1F52E}', color: 'from-violet-500 to-indigo-500' },
}
